basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING STARTS HERE

app_name = 'basic_app'

urlpatterns = [
    path('other/', views.other,name='other'),
    path('relative/', views.relative,name='relative'),
]

learn_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path("",views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
]

basic_app/models.py
from django.db import models

# Create your models here.

basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    # this is a very common templates filter example 
    context_dict = {'text':'hello world', 'number': 100}

    return render(request,'basic_app/index.html',context=context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset='utf-8'>
    <title>Base Page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-fixed-top">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'images/HG.jpg'%}" width="30" height="30" alt="" loading="lazy" />HG
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin Login</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-danger" type="submit">Search</button>
          </form>
        </div>
      </nav>
      <div class="container">
  
      {% block content %}
      <!-- This is where you'll put your page content. Leave it blank for now. -->
      {% endblock %}
      
      </div>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to Index Page!</h1>
    </div>
    <h2>{{ text|title }}</h2>
    <h2>{{ text|upper }}</h2>
    <h2>{{ text|lower }}</h2>
    <h2>{{ text|length }}</h2>
    <h2>{{ number }}</h2>
    <h2>{{ number|add:'99' }}</h2>
    <p></p>
    <p></p>
    <h2>{{ text|cut:'hello' }}</h2>
    <h2>{{ text|cut:'world' }}</h2>
    <h2>{{ text|cut:'hello'|title }}</h2>
    
</div>
{% endblock %}

templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block content %}
    
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Other</h1>
            <h2>This a is a example of template inheritance </h2>
        </div>
    </div>
    
    {% endblock %}
</body>
</html>

templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Relative</title>
</head>
<body>
    <h1>Welcome to Relative</h1>
    <!-- important notes here 'basic_app' <-- this name must be match with the name which we define
    in basic_app.urls file in the starting like app_name = 'basic_app' and other.html name match with after :-->
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a>
    <a href="{% url 'index' %}">LINK TO INDEX PAGE</a>

</body>
</html>